# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 823fbe670f85aaf6f04baf64c12236c15850ae9639e3266286b9d4d57678ff28fc4ed807f1cf27311dc98f5fae077c59ce95e1666f674a5d003bb83ba78fcd6e

test:
  secret_key_base: 8bcb9688bb0216d63a31381f676edf8852d0442a436407ab561d372fd88197f3a76e71c5cf982c30aaa39530036f95d8f33906b9ef8f369bec57cfccd0e6a7cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
